name: 🚀Release
run-name: ${{ vars.PROJECT_NAME }} Production Release ${{ inputs.dry-run == true && '(Dry Run)' || '' }}


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run - Check to run the workflow without creating a release.
        required: false
        default: false
        type: boolean


jobs:
  get_and_validate_version:
    name: Get And Validate Version
    runs-on: ubuntu-26.04
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Get Version
        id: get-version
        uses: KinsonDigital/Infrastructure/actions/get-version@5dade832543507f6ee8f9123794ca7dd3b317e67 # v19.0.1
        with:
          version-file-path: "${{ github.workspace }}/${{ vars.PROJECT_NAME }}/${{ vars.PROJECT_NAME }}.csproj"
          cache-enabled: false

      - name: Validate Version
        id: validate-version
        uses: KinsonDigital/Infrastructure/actions/validate-version@5dade832543507f6ee8f9123794ca7dd3b317e67 # v19.0.1
        with:
          version: "v${{ steps.get-version.outputs.version }}"
          release-type: "Production"
          cache-enabled: false


  validate_release:
    name: Validate Release
    needs: [get_and_validate_version]
    uses: KinsonDigital/Infrastructure/.github/workflows/validate-release.yml@5dade832543507f6ee8f9123794ca7dd3b317e67 # v19.0.1
    with:
      owner-name: "${{ vars.ORGANIZATION_NAME }}"
      repo-name: "${{ vars.PROJECT_NAME }}"
      release-type: "Production"
      version: "${{ needs.get_and_validate_version.outputs.version }}"
      relative-release-notes-file-path: "ReleaseNotes/ProductionReleases/${{ vars.RELEASE_NOTES_FILE_NAME_PREFIX }}${{ needs.get_and_validate_version.outputs.version }}.md"
      is-dotnet-project: true
    secrets:
      cicd-pat: "${{ secrets.CICD_TOKEN }}"


  get_release_notes_path:
    name: Get Release Notes Dir Path
    needs: [get_and_validate_version]
    runs-on: ubuntu-latest
    outputs:
      release-notes-dir-path: ${{ steps.get-dir-path.outputs.release-notes-dir-path }}
    steps:
      - name: Get Dir Path
        id: get-dir-path
        run: |
          $dirPath = "${{ vars.PROD_RELATIVE_RELEASE_NOTES_DIR_PATH }}";
          "release-notes-dir-path=$dirPath" >> $env:GITHUB_OUTPUT;


  build_vel_empty_template_proj:
    name: Build VelaptorEmpty Proj Template
    needs: [get_and_validate_version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: "${{ vars.NET_SDK_VERSION }}"

      - name: Build Project
        run: |
          $projFilePath = "${{ github.workspace }}/VelaptorTemplates/Templates/VelaptorEmpty/VelaptorEmpty.csproj";
          dotnet build $projFilePath -c Release;


  build_vel_render_texture_proj:
    name: Build VelaptorRenderTexture Proj Template
    needs: [get_and_validate_version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: "${{ vars.NET_SDK_VERSION }}"

      - name: Build Project
        run: |
          $projFilePath = "${{ github.workspace }}/VelaptorTemplates/Templates/VelaptorRenderTexture/VelaptorRenderTexture.csproj";
          dotnet build $projFilePath -c Release;


  run_release:
    name: Performing Production Release of ${{ vars.PROJECT_NAME }}
    needs: [get_and_validate_version, get_release_notes_path, build_vel_empty_template_proj, build_vel_render_texture_proj]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: "${{ vars.NET_SDK_VERSION }}"

      - name: Setup Nuget
        uses: NuGet/setup-nuget@fd55a6f3b34392fa83fde1454582407d8c714123 # v4.0.0

      - name: Create Nuget Package
        run: |
          dotnet pack `
            "${{ github.workspace }}/${{ vars.PROJECT_NAME }}/${{ vars.PROJECT_NAME }}.csproj" `
            -o "${{ github.workspace }}" `
            -c Release `
            -p:IncludeSymbols=true;

      - name: Publish Nuget Package
        if: ${{ inputs.dry-run == false }}
        run: |
          $version = "${{ needs.get_and_validate_version.outputs.version }}";
          $version = $version.StartsWith("v") ? $version.Substring(1) : $version;

          # Push the nuget package
          dotnet nuget push `
            "${{ github.workspace }}/${{ vars.ORGANIZATION_NAME }}.${{ vars.PROJECT_NAME }}.$version.nupkg" `
            --api-key ${{ secrets.NUGET_ORG_API_KEY }} `
            --source https://api.nuget.org/v3/index.json;

      - name: Create GitHub Release ${{ inputs.dry-run == true && '(Dry Run)' || '' }}
        if: ${{ inputs.dry-run == false }}
        uses: ncipollo/release-action@v1
        with:
          name: "🚀Production - ${{ needs.get_and_validate_version.outputs.version }}"
          tag: ${{ needs.get_and_validate_version.outputs.version }}
          owner: ${{ vars.ORGANIZATION_NAME }}
          repo: ${{ vars.PROJECT_NAME }}
          bodyFile: "${{ github.workspace }}/ReleaseNotes/ProductionReleases/Release-Notes-v${{ needs.get_and_validate_version.outputs.version }}.md"
          prerelease: false

      - name: Set Up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ vars.DENO_VERSION }}

      - name: Create Script URL
        id: script-url
        run: |
          # Construct the URL to the organizations CICD scripts
          $url = "${{ vars.SCRIPT_BASE_URL }}/${{ vars.CICD_SCRIPTS_VERSION }}/${{ vars.SCRIPT_RELATIVE_DIR_PATH }}";
          $url = $url.Replace("\", "/").Replace("//", "/");
          $url = $url.EndsWith("/") ? $url.Substring(0, $url.Length - 1) : $url;
          
          Write-Host "::notice::DotNet Lib Release Script URL: $url";
          "url=$url" >> "$env:GITHUB_OUTPUT";


  send_release_announcements:
    name: Send Release Announcements
    runs-on: ubuntu-26.04
    needs: [get_and_validate_version, validate_release,
      build_vel_empty_template_proj, build_vel_render_texture_proj,
      run_release]
    if: ${{ inputs.dry-run == false }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Send X Release Announcement
        uses: KinsonDigital/Infrastructure/actions/send-x-release-announcement@5dade832543507f6ee8f9123794ca7dd3b317e67 # v19.0.1
        continue-on-error: true
        with:
          repo-owner: ${{ vars.ORGANIZATION_NAME }}
          project-name: ${{ vars.PROJECT_NAME }}
          version: ${{ needs.get_and_validate_version.outputs.version }}
          website-url: ${{ vars.WEBSITE_URL }}
          local-post-template-file-path: "${{ github.workspace }}/templates/release-announcement.txt"
          discord-invite-code: ${{ vars.DISCORD_INVITE_CODE }}
          access-token-key: ${{ secrets.X_ACCESS_TOKEN_KEY }}
          access-token-secret: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          consumer-api-key: ${{ secrets.X_CONSUMER_API_KEY }}
          consumer-api-secret: ${{ secrets.X_CONSUMER_API_SECRET }}
          cache-enabled: false
          github-token: ${{ secrets.CICD_TOKEN }}

      - name: Send Bluesky Release Announcement
        uses: KinsonDigital/Infrastructure/actions/send-bluesky-release-announcement@5dade832543507f6ee8f9123794ca7dd3b317e67 # v19.0.1
        with:
          repo-owner: ${{ vars.ORGANIZATION_NAME }}
          project-name: ${{ vars.PROJECT_NAME }}
          version: ${{ needs.get_and_validate_version.outputs.version }}
          website-url: ${{ vars.WEBSITE_URL }}
          local-post-template-file-path: "${{ github.workspace }}/templates/release-announcement.txt"
          discord-invite-code: ${{ vars.DISCORD_INVITE_CODE }}
          service: ${{ vars.BLUESKY_SERVICE }}
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
          cache-enabled: false
          github-token: ${{ secrets.CICD_TOKEN }}


  process_milestone:
    name: Process Milestone ${{ inputs.dry-run == true && '(Dry Run)' || '' }}
    needs: [get_and_validate_version, validate_release, build_vel_empty_template_proj, build_vel_render_texture_proj, run_release]
    if: ${{ inputs.dry-run == false }}
    uses: KinsonDigital/Infrastructure/.github/workflows/process-milestone.yml@5dade832543507f6ee8f9123794ca7dd3b317e67 # v19.0.1
    with:
      owner-name: ${{ vars.ORGANIZATION_NAME }}
      repo-name: ${{ vars.PROJECT_NAME }}
      version: ${{ needs.get_and_validate_version.outputs.version }}
    secrets:
      cicd-pat: ${{ secrets.CICD_TOKEN }}
